import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "../app/globals.css";

import Navigation from "@/components/Navigation";
import SmoothScroll from "@/components/SmoothScroll";
import Footer from "@/components/FooterSection";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Hooc-Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // FIX: Added suppressHydrationWarning here
    <html lang="en" suppressHydrationWarning>
     <body suppressHydrationWarning
        className={`
          ${inter.variable} 
          ${playfair.variable} 
          ${inter.variable} 
          ${playfair.variable} 
          antialiased
          `}
          >
        <Navigation />
      
       <SmoothScroll>
          {children}
        </SmoothScroll>
       <Footer/>
       <Toaster position="bottom-right" />
      </body>
    </html>
  );
}